### ISSUE TITLE
Error while combine the files and save them

### ISSUE THREAD

**Issue by hellosakshi** [UBC-MDS/DSCI525_Group14#17]
Hello group,

As discussed, I cloned the repository again. However, I am getting the same error while combining and saving the files. Below is the error details:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<timed exec> in <module>

C:\miniconda3\envs\525\lib\site-packages\pandas\core\reshape\concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    283     ValueError: Indexes have overlapping values: ['a']
    284     """
--> 285     op = _Concatenator(
    286         objs,
    287         axis=axis,

C:\miniconda3\envs\525\lib\site-packages\pandas\core\reshape\concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    337             objs = [objs[k] for k in keys]
    338         else:
--> 339             objs = list(objs)
    340 
    341         if len(objs) == 0:

<timed exec> in <genexpr>(.0)

IndexError: list index out of range
```

My code:
```
combined_file_path = output_directory + "combined_data.csv"
%%time
%memit

# Combine files and save
files = glob.glob(output_directory + "*_daily_rainfall_NSW.csv")
df = pd.concat(
    (
        pd.read_csv(file, index_col=0).assign(
            model=re.findall(r"/(.*)_daily_rainfall", file)[0]
        )
        for file in files
    )
)
df.to_csv(combined_file_path)
```

**Comment by sbabicki** [comment]
@hellosakshi Did you remove `/figshareairline` folder before running from the beginning? I think `ValueError: Indexes have overlapping values: ['a']` could occur if `combined_data.csv` already exists.

**Comment by hellosakshi** [comment]
@sbabicki I deleted /figshareairline folder and run the notebook again. However, I received the same error.

**Comment by sbabicki** [comment]
Are you using a windows computer or a mac? If you are using windows maybe it's something to do with the bracket "/" in the regular expression?

**Comment by hellosakshi** [comment]
Hello @sbabicki I fixed the above problem but now I received another issue. My drive is full. I am asking a friend to help me in running the file.

![error](https://user-images.githubusercontent.com/51753495/113503018-30f8d400-94e4-11eb-9bfb-4b3abdf088a8.PNG)

**Comment by sbabicki** [comment]
If it's just failing because you don't have enough space that is totally
fine! We called attention to this issue in the notebook so now we can show
that the reason that you can't run it is that you don't have enough space
available on your computer. I had the same problem earlier and had to
delete some files to make space, but I don't think it's necessary for you
to run the script since we already have 3 different runtime results
cateloged.

Thanks for looking into this!

**Comment by hellosakshi** [comment]
@sbabicki In that case, I am not uploading the file. We don't need any changes in our repository. My friend is running the file for me and send it later. 

Thank you very much for helping me.
