### ISSUE TITLE
Consistency with %%

### ISSUE THREAD

**Issue by hellosakshi** [UBC-MDS/DSCI525_Group14#24]
Hello everybody,

I noticed that we are not using %% consistently. We are using only one % at some places and %% at some other places. I checked couple of notebooks and I noticed that correct usage is %%. I dont know if it matters.

I still have issues and my friend is running the file for me. Once I get updated. I will post here.

**Comment by sbabicki** [comment]
The use of % and %% in different places is intentional. Using % prints the
cell output, using %% does not.

**Comment by hellosakshi** [comment]
Thank you very much for letting me know. I didn't know the difference. I am closing this ticket.

**Comment by hellosakshi** [comment]
resolved
