### ISSUE TITLE
3. Set up ML Model

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/DSCI525_Group14#34]
3. Develop a ML model using scikit-learn.
rubric={correctness:25}

Upload this notebook to your jupyterHub (TLJH in your EC2) from your previous milestone and follow instruction given there. https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/Milestone3-Task3.ipynb

**Comment by zmerpez** [comment]
Done!
