### ISSUE TITLE
Perform a simple EDA in R

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/DSCI525_Group14#6]
### 6. Perform a simple EDA in R
rubric={correctness:15,reasoning:10}

1. Pick an approach to transfer the dataframe from python to R. 
    - [Parquet file](http://parquet.apache.org)
    - [Feather file](https://arrow.apache.org/docs/python/feather.html)
    - [Pandas exchange](https://rpy2.github.io/doc/latest/html/interactive.html)
    - [Arrow exchange](https://github.com/rpy2/rpy2-arrow)
2. Discuss why you chose this approach over others.

**Comment by zmerpez** [comment]
Fixing bug:
Try:

$ conda install -c r r-essentials

Then:

$ conda install -c r rpy2

**Comment by sbabicki** [comment]
@ChuckHo777 I didn't review this question as closely as part 5, are we good to close this issue?

**Comment by ChuckHo777** [comment]
@sbabicki  @zmerpez  @hellosakshi  I just updated the reasoning for Section 6 with a PR, let me know if you want to edit or add anything.
